config/routes.rb
Rails.application.routes.draw do
  root 'chatrooms#index'

  get 'signin', to: 'sessions#new', as: 'signin'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  mount ActionCable.server => '/cable'

  resources :chatrooms, params: :slug
  resources :messages
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :chatrooms, through: :messages
  has_many :messages
  validates :username, presence: true, uniqueness: true

  def self.authenticate(username = "")
    user = User.find_by_username(username)
    user ? user : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user
  protect_from_forgery with: :exception

  def authenticate_user
    if session[:user_id]
      @current_user = User.find session[:user_id]
      return true
    else
      redirect_to signin_path
      return false
    end
  end

  def save_login_state
    if session[:user_id]
      redirect_to root_path
      return false
    else
      return true
    end
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatroom = Chatroom.find params[:id]
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
    message = Message.new message_params
    message.user = @current_user
    if message.save
      ActionCable.server.broadcast 'messages', message: message.content, user: message.user.username
      head :ok
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :chatroom_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate_user, raise: false
  before_filter :save_login_state, only: [:new, :create]

  def new
  end

  def create
    authorized_user = User.authenticate(params[:session][:username])
    if authorized_user
      session[:user_id] = authorized_user.id
      redirect_to root_path, notice: "Welcome back, #{authorized_user.username}"
    else
      flash.now[:alert] = "Invalid Username"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate_user, raise: false
  before_filter :save_login_state, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You're signed up!"
    else
      flash.now[:alert] = "There was an error signing you up... try again?"
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/index.html.erb
<% if @current_user %>
  <h3>Hey, <%= @current_user.username %>. <%= link_to "Sign out?", signout_path, method: :delete %></h3>
<% else %>
  <%= link_to "Sign Up!", new_user_path %> | <%= link_to "Sign In!", signin_path %>
<% end %>

<br>
<h3>Chatrooms:</h3>
<ul>
  <% @chatrooms.each do |room| %>
    <li>
      <%= link_to "Chatroom #{room.id}", chatroom_path(room) %>
    </li>
  <% end %>
</ul>

app/views/chatrooms/show.html.erb
<h1><%= "Chatroom #{@chatroom.id} - #{@chatroom.topic}" %></h1>

<h3>Messages:</h3>
<div class="panel-body" id="messages">
  <%= render partial: 'messages/message', collection: @chatroom.messages %>
</div>

<hr>
<%= form_for @message, remote: true, authenticity_token: true do |f| %>
  <%= f.label :your_message %>:
  <%= f.text_area :content, class: "form-control", data: { textarea: "message" } %>
  <%= f.hidden_field :chatroom_id, value: @chatroom.id %>
  <%= f.submit "send", class: "btn btn-primary", data: { send: "message" } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionCableExample</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] || flash[:alert] %>
      <div class="<%= "flash-container #{flash.alert ? 'error' : ''}".strip %>">
        <p class="<%= "flash-message #{flash.alert ? 'error' : ''}".strip %>"><%= "#{flash.notice}#{flash.alert}" %></p>
      </div><!-- End flash container -->
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p class="message"><strong><%= message.user.username %>: </strong><%= message.content %></p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |form| %>
  <%= form.label :username %>
  <%= form.text_field :username, required: "required" %>
  <%= form.submit "Sign Up" %>
<% end %>